### ISSUE TITLE
CMake configuration writes directly to installation directory

### ISSUE THREAD

**Issue by sogartar** [oneapi-src/oneCCL#82] opened 2022-11-04 14:56 UTC
[Here](https://github.com/oneapi-src/oneCCL/blob/debdc21aba5230ed0ea945b14d8f61dfeedfb535/CMakeLists.txt#L269) cmake writes to the install directory which usually is owned by `root`. Usually building is not done by `root`. This causes a write failure.
```
if (BUILD_CONFIG)
    configure_file("cmake/templates/oneCCLConfig.cmake.in"
                   "${CCL_INSTALL_LIB}/cmake/oneCCL/oneCCLConfig.cmake"
                   COPYONLY)
    configure_file("cmake/templates/oneCCLConfigVersion.cmake.in"
                   "${CCL_INSTALL_LIB}/cmake/oneCCL/oneCCLConfigVersion.cmake"
                   @ONLY)
endif()
```

This does not manifest under default conditions because of this dubious [change](https://github.com/oneapi-src/oneCCL/blob/debdc21aba5230ed0ea945b14d8f61dfeedfb535/CMakeLists.txt#L64) of `CMAKE_INSTALL_PREFIX`.

**Comment by nikitaxgusev** [comment] 2022-12-13 10:00
Hello @sogartar, can you, please, provide the steps how you get the hit of this issue?

**Comment by sogartar** [comment] 2022-12-13 17:15
You should use for example
```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local ...
```
This is the default place on Unix.

**Comment by ksenyako** [comment] 2023-01-02 16:07
Hi @sogartar I was able to reproduce the issue with  ` -DCMAKE_INSTALL_PREFIX=/usr` partly, on `make` step I got the error which you are talking about. After some reworking `CMakeLists.txt` I got permission issue on `make install` step because `/usr` folder is owned by root. I suppose the fix will be useful, but can you please provide detailed step by step reproducer for verification purposes?

**Comment by ksenyako** [comment] 2023-04-03 12:48
Hi @sogartar, the fix was merged, could you please try updated oneCCL?

**Closed** 2023-09-04 13:35 UTC
